### ISSUE TITLE
Static error

### ISSUE THREAD

**Issue by hose1021** [DevHub-Azerbaycan/python_web_site#15]
Error with static files when running in docker

**Comment by Maharramoff** [comment]
@hose1021  Issue-nin descriptionu aydın deyil. Amma təxmin edirəm ki, nginx-lə bağlıdır. nginx.conf 80 listen edir. Bunu dəyişib [neytral bir port](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) təyin etmək lazımdır. Məsələn, 9002. 80-ci port çox proqramlarda default gəlir. Bunu dəyişdikdən sonra isə yml-də də neytral bir port təyin edirik. 
```yml
  nginx:
    ....
    ports:
      - "1314:9002"
```
Bundan sonra konflikt olma ehtimalı demək olar ki, yoxdur. App http://localhost:1314 ünvanında işləyəcək. 80-ci port productionda lazım olacaq.

**Comment by hose1021** [comment]
Prob eliyerem

**Comment by hose1021** [comment]
Solved: #21
